package com.example.petoibittlecontrol.commands

object voiceCommandMap {
    val commandMap = mapOf(
        "înainte" to BleCommands.WALK_FORWARD,
        "înapoi" to BleCommands.BACKWARD,
        "stânga" to BleCommands.WALK_LEFT,
        "dreapta" to BleCommands.WALK_RIGHT,
        "așteaptă" to BleCommands.REST,
        "echilibru" to BleCommands.KBALANCE,
        "ridicare fund" to BleCommands.BUTTUP,
        "calibrare" to BleCommands.CALIBRATION,
        "căzut" to BleCommands.DROPPED,
        "ridicat" to BleCommands.LIFTED,
        "aterizare" to BleCommands.LANDING,
        "șezut" to BleCommands.SIT,
        "întindere" to BleCommands.STRETCH,
        "înaintare rapidă" to BleCommands.BOUND_FORWARD,
        "înapoi stânga" to BleCommands.BACKWARD_LEFT,
        "târâre înainte" to BleCommands.CRAWL_FORWARD,
        "târâre stânga" to BleCommands.CRAWL_LEFT,
        "salt înainte" to BleCommands.GAP_FORWARD,
        "salt stânga" to BleCommands.GAP_LEFT,
        "halloween" to BleCommands.HALLOWEEN,
        "salt înainte" to BleCommands.JUMP_FORWARD,
        "împins înainte" to BleCommands.PUSH_FORWARD,
        "împins stânga" to BleCommands.PUSH_LEFT,
        "tropăit înainte" to BleCommands.TROT_FORWARD,
        "tropăit stânga" to BleCommands.TROT_LEFT,
        "pas pe loc" to BleCommands.STEP_ORIGIN,
        "întoarcere stânga" to BleCommands.SPING_LEFT,
        "furios" to BleCommands.ANGRY,
        "salt înapoi" to BleCommands.BACKFLIP,
        "verificare" to BleCommands.CHECK,
        "săpat" to BleCommands.DIG,
        "salt înainte" to BleCommands.FRONT_FLIP,
        "salut" to BleCommands.HI,
        "fă pe mortul" to BleCommands.PLAY_DEAD,
        "urinat" to BleCommands.PEE,
        "flotări" to BleCommands.PUSH_UPS,
        "flotări pe o mână" to BleCommands.PUSH_UPS_ONE_HAND,
        "recuperare" to BleCommands.RECOVER,
        "rostogolire" to BleCommands.ROLL,
        "test" to BleCommands.TEST,
    )
}