package com.example.petoibittlecontrol.commands

object voiceCommandMap {
    val commandMap = mapOf(
        "înainte" to BleCommands.WALK_FORWARD,
        "înapoi" to BleCommands.BACKWARD,
        "stânga" to BleCommands.WALK_LEFT,
        "dreapta" to BleCommands.WALK_RIGHT,
        "așteaptă" to BleCommands.REST,
        "echilibru" to BleCommands.KBALANCE,
        "ridicare fund" to BleCommands.BUTTUP,
        "calibrare" to BleCommands.CALIBRATION,
        "căzut" to BleCommands.DROPPED,
        "ridicat" to BleCommands.LIFTED,
        "aterizare" to BleCommands.LANDING,
        "șezut" to BleCommands.SIT,
        "întindere" to BleCommands.STRETCH,
        "sus" to BleCommands.UP,
        "zero" to BleCommands.ZERO,
        "sărit înainte" to BleCommands.BOUND_FORWARD,
        "înapoi stânga" to BleCommands.BACKWARD_LEFT,
        "târâre înainte" to BleCommands.CRAWL_FORWARD,
        "târâre stânga" to BleCommands.CRAWL_LEFT,
        "salt peste gol înainte" to BleCommands.GAP_FORWARD,
        "salt peste gol stânga" to BleCommands.GAP_LEFT,
        "halloween" to BleCommands.HALLOWEEN,
        "salt înainte" to BleCommands.JUMP_FORWARD,
        "împins înainte" to BleCommands.PUSH_FORWARD,
        "împins stânga" to BleCommands.PUSH_LEFT,
        "trot înainte" to BleCommands.TROT_FORWARD,
        "trot stânga" to BleCommands.TROT_LEFT,
        "pas înainte" to BleCommands.STEP_ORIGIN,
        "întoarcere stânga" to BleCommands.SPING_LEFT,
        "furios" to BleCommands.ANGRY,
        "salt înapoi" to BleCommands.BACKFLIP,
        "box" to BleCommands.BOXING,
        "urale" to BleCommands.CHEERS,
        "verificare" to BleCommands.CHECK,
        "vino aici" to BleCommands.COME_HERE,
        "săpat" to BleCommands.DIG,
        "salt înainte" to BleCommands.FRONT_FLIP,
        "cinci" to BleCommands.HIGH_FIVE,
        "băiat cuminte" to BleCommands.GOOD_BOY,
        "stând pe mâini" to BleCommands.HANDSTAND,
        "îmbrățișare" to BleCommands.HUG,
        "salut" to BleCommands.HI,
        "strângere de mână" to BleCommands.HAND_SHAKE,
        "mâinile sus" to BleCommands.HANDS_UP,
        "salt" to BleCommands.JUMP,
        "lovitură" to BleCommands.KICK,
        "salt peste" to BleCommands.LEAP_OVER,
        "mers pe lună" to BleCommands.MOON_WALK,
        "dat din cap" to BleCommands.NOD,
        "joc de-a mortul" to BleCommands.PLAY_DEAD,
        "urinat" to BleCommands.PEE,
        "flotări" to BleCommands.PUSH_UPS,
        "flotări pe o mână" to BleCommands.PUSH_UPS_ONE_HAND,
        "recuperare" to BleCommands.RECOVER,
        "rostogolire" to BleCommands.ROLL,
        "scărpinare" to BleCommands.SCRATCH,
        "mirosit" to BleCommands.SNIFF,
        "fii masă" to BleCommands.BE_TABLE,
        "test" to BleCommands.TEST,
        "dat din cap" to BleCommands.WAVE_HEAD,
        "toate încheieturile la zero" to BleCommands.ALL_JOINT_AT_0
    )
}